import React from 'react';
import ReactDOM from 'react-dom';
import Remarkable from 'remarkable';

import CommentForm from './commentForm.js';
import CommentList from './commentList.js';
import { store, ActionTools } from './flux';

module.exports = React.createClass({
	
  handleCommentSubmit: function(comment) {
    var comments = this.state.data;
    // Optimistically set an id on the new comment. It will be replaced by an
    // id generated by the server. In a production application you would likely
    // not use Date.now() for this and would have a more robust system in place.
    comment.id = Date.now();
    var newComments = comments.concat([comment]);
    this.setState({data: newComments});
	store.dispatch(ActionTools.addComment(comment));
  },
	componentWillMount() {
    	this.unsubscribe = store.subscribe(() => {
    	    this.setState({
        	    data: store.getState().data
        	});
    	});
	},
	componentWillUnmount: function() {
    	this.unsubscribe();
	},
  getInitialState: function() {
    return {data: []};
  },

  render: function() {
    return (
      <div className="commentBox">
        <h1>Comments</h1>
        <CommentList data={this.state.data} />
        <CommentForm onCommentSubmit={this.handleCommentSubmit} />
      </div>
    );
  }
});

